language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.12
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=RELEASE
matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true


before_install:
  - git clone https://github.com/zenspider/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

install:

before_script:

script:
  - make test

after_script:
